services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.all
    image: quran-all:latest
    container_name: quran-all
    environment:
      - QURAN_DB_PATH=/data/quran.db
      - QURAN_API_BIND=:8080
      - QURAN_WEB_BIND=:8090
    ports: ["8080:8080","8090:8090"]
    volumes:
      - ./data:/data
